CREATE TABLE UserDetail (
	userID		INT				NOT NULL	IDENTITY(1,1),
	userName	VARCHAR(255)	NOT NULL,
	email		VARCHAR(255)	NOT NULL,
	password	VARCHAR(255)	NOT NULL,

	PRIMARY KEY(userID)
);

CREATE TABLE Post (
	postID		INT				NOT NULL	IDENTITY(1,1),
	authorID	INT				NOT NULL,
	title		VARCHAR(255)	NOT NULL,
	content		VARCHAR(255)	NOT NULL,
	createdAt	DATETIME		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	updatedAt	DATETIME,
	likes		INT							DEFAULT 0,	

	PRIMARY KEY(postID),
	FOREIGN KEY(authorID) REFERENCES UserDetail(userID)
);

ALTER TABLE Post 
ALTER COLUMN createdAt DATETIME2 NOT NULL;
ALTER TABLE Post 
ADD CONSTRAINT DF_Post_createdAt DEFAULT CURRENT_TIMESTAMP FOR createdAt;

UPDATE Post
SET isLiked = 0
WHERE isLiked IS NULL;

ALTER TABLE Post
ALTER COLUMN isLiked INT NOT NULL;
ALTER TABLE Post
ADD CONSTRAINT CHK_isLiked CHECK (isLiked in (0,1));
ALTER TABLE Post
ADD CONSTRAINT DF_isLiked DEFAULT 0 FOR isLiked;

ALTER TABLE Post
ALTER COLUMN content NVARCHAR(MAX) NOT NULL;

select * from UserDetail;

SELECT * FROM Post;

SELECT CURRENT_TIMESTAMP;